import { Settings } from '@/lib/types/settings'

export const defaultSettings: Settings = {
  visualization: {
    nodes: {
      color: '#3e82f7',
      defaultSize: 500,
      minSize: 200,
      maxSize: 700,
      highlightColor: '#4f90ff',
      outlineWidth: 2,
      outlineColor: '#ffffff',
      selectedColor: '#ff9900',
    },
    edges: {
      width: 2,
      color: '#ffffff',
      highlightColor: '#4f90ff',
      opacity: 0.7,
      showLabels: false,
      arrowSize: 1,
      dashSize: 1,
      gapSize: 0.5,
    },
    physics: {
      enabled: true,
      attraction: 0.01, 
      repulsion: 5,
      damping: 0.9,
      friction: 0.9,
      gravity: 0,
      springLength: 100,
      iterations: 3,
    },
    rendering: {
      shadows: false,
      antialias: true,
      pixelRatio: 1,
      enableBloom: true,
      bloomStrength: 1.2,
      bloomThreshold: 0.4,
      bloomRadius: 0.8,
    },
    labels: {
      enabled: true,
      size: 14,
      color: '#ffffff',
      backgroundColor: '#000000',
      showDistance: 1000,
      fadeDistance: 2000,
    },
    bloom: {
      enabled: true,
      strength: 1.2,
      radius: 0.8,
      threshold: 0.4,
    },
    sceneBackground: 0x000000, // Using hex number format instead of string
    camera: {
      fov: 75,
      near: 0.1,
      far: 10000,
      position: { x: 0, y: 0, z: 500 },
      lookAt: { x: 0, y: 0, z: 0 },
    },
    hologram: {
      color: '#3e82f7',
      opacity: 0.7,
      ringOpacity: 0.7,
      sphereSizes: [40, 80],
      enableTriangleSphere: false,
      triangleSphereSize: 100,
      triangleSphereOpacity: 0.5,
      ringRotationSpeed: 0.5,
      globalRotationSpeed: 0.5,
    },
    icons: {
      enabled: true,
      color: '#ffffff',
      size: 1.0,
      opacity: 0.8,
    },
    metrics: {
      enabled: false,
      refreshRate: 1000,
      position: 'top-right',
    },
    showStats: false,
    showAxes: false,
    showGrid: false,
    
  },
  system: {
    websocket: {
      reconnectInterval: 3000,
      maxReconnectAttempts: 5,
      protocol: 'json',
    },
    debug: {
      enabled: true,
      enableDataDebug: false,
      enableWebsocketDebug: false,
      logBinaryHeaders: false,
      logFullJson: false,
      showPerformance: false,
      showDataUpdates: false,
      logLevel: 'info',
      logFormat: 'json',
    },
    persistSettings: true,
    apiEndpoint: '/api',
  },
  auth: {
    enabled: true,
    provider: 'nostr',
    required: false,
  },
  xr: {
    enabled: false,
    handInteraction: true,
    controllerModel: 'default',
    movementSpeed: 1.0,
    teleportEnabled: true,
    roomScale: true,
    showFloor: true,
    interactionDistance: 1.5,
    grabThreshold: 0.1,
    controllerRayColor: '#ffffff',
    controllerPointerSize: 0.01,
    hapticFeedback: true
  }
}
