import { Settings } from '@/lib/types/settings'

export const defaultSettings: Settings = {
  visualization: {
    nodes: {
      baseColor: '#3e82f7',
      metalness: 0.5,
      opacity: 0.9,
      roughness: 0.5,
      sizeRange: [200, 700],
      quality: 'medium',
      enableInstancing: true,
      enableHologram: false,
      enableMetadataShape: false,
      enableMetadataVisualization: false,
    },
    edges: {
      arrowSize: 1,
      baseWidth: 2,
      color: '#ffffff',
      enableArrows: true,
      opacity: 0.7,
      widthRange: [2, 3],
      quality: 'medium',
      enableFlowEffect: false,
      flowSpeed: 0.5,
      flowIntensity: 0.5,
      glowStrength: 0.3,
      distanceIntensity: 0.5,
      useGradient: false,
      gradientColors: ['#ff0000', '#00ff00'],
    },
    physics: {
      attractionStrength: 0.01,
      boundsSize: 50,
      collisionRadius: 1,
      damping: 0.9,
      enableBounds: true,
      enabled: true,
      iterations: 3,
      maxVelocity: 0.1,
      repulsionStrength: 5,
      springStrength: 0.01,
      repulsionDistance: 10,
      massScale: 1,
      boundaryDamping: 0.8,
    },
    rendering: {
      ambientLightIntensity: 0.3,
      backgroundColor: '#000000',
      directionalLightIntensity: 0.7,
      enableAmbientOcclusion: true,
      enableAntialiasing: true,
      enableShadows: false,
      environmentIntensity: 0.5,
      shadowMapSize: '2048',
      shadowBias: 0,
      context: 'desktop',
    },
    animations: {
      enableMotionBlur: false,
      enableNodeAnimations: true,
      motionBlurStrength: 0.5,
      selectionWaveEnabled: true,
      pulseEnabled: true,
      pulseSpeed: 0.7,
      pulseStrength: 0.3,
      waveSpeed: 0.5,
    },
    labels: {
      desktopFontSize: 14,
      enableLabels: true,
      textColor: '#ffffff',
      textOutlineColor: '#000000',
      textOutlineWidth: 2,
      textResolution: 32,
      textPadding: 5,
      billboardMode: 'camera',
    },
    bloom: {
      edgeBloomStrength: 1,
      enabled: true,
      environmentBloomStrength: 0.5,
      nodeBloomStrength: 1.5,
      radius: 0.8,
      strength: 1.2,
      threshold: 0.4,
    },
    hologram: {
      ringCount: 3,
      ringColor: '#3e82f7',
      ringOpacity: 0.7,
      sphereSizes: [40, 80],
      ringRotationSpeed: 0.5,
      enableBuckminster: false,
      buckminsterSize: 100,
      buckminsterOpacity: 0.5,
      enableGeodesic: false,
      geodesicSize: 100,
      geodesicOpacity: 0.5,
      enableTriangleSphere: false,
      triangleSphereSize: 100,
      triangleSphereOpacity: 0.5,
      globalRotationSpeed: 0.5,
    },
  },
  system: {
    websocket: {
      reconnectAttempts: 5,
      reconnectDelay: 3000,
      binaryChunkSize: 1024,
      compressionEnabled: true,
      compressionThreshold: 1024,
      updateRate: 30,
    },
    debug: {
      enabled: false,
      enableDataDebug: false,
      enableWebsocketDebug: false,
      logBinaryHeaders: false,
      logFullJson: false,
      enablePhysicsDebug: false,
      enableNodeDebug: false,
      enableShaderDebug: false,
      enableMatrixDebug: false,
      enablePerformanceDebug: false,
    },
  },
  xr: {
    enabled: false,
    handTracking: true,
    controllerModel: 'default',
    renderScale: 1.0,
    interactionDistance: 1.0,
    locomotionMethod: 'teleport',
    teleportRayColor: '#3e82f7',
    enableHaptics: true,
    displayMode: 'stereo',
  }
}